v3 checkpoint

diff --git a/vs_constants b/vs_constants
--- a/vs_constants
+++ b/vs_constants
@@ -5,6 +5,11 @@ function xstub {
     echo "vimsane.xstub: $*" >&2
 }
 
+function errExit {
+    echo "ERROR: $*" >&2
+    exit 1
+}
+
 function prompt_flow {
     # Prints msg to stderr with text flow, and
     # then prints a prompt and waits for user reply.
@@ -22,6 +27,22 @@ function prompt_flow {
 export VimsaneVersion=3  # The current 'production' version of Vimsane
 export VimsaneUserVersion=0  # The current version installed for this user
 export VimsaneStateRoot="$HOME/.vimsane"
-[[ -z $VimsaneCodeRoot ]] && VimsaneCodeRoot=/bb/sys/package/v/vimsanepkg/current
+[[ -z $VimsaneCodeRoot ]] && VimsaneCodeRoot=/bb/bin/trnkit/vimsane
 export VimsaneCodeRoot
+export VimsaneCoreRepo="https://github.com/sanekits/vimsane-cfg.git"
+export github_proxy="devproxy.bloomberg.com:82"
+
+XGIT=/opt/bb/bin/git
+
+function vs_github_clone {
+    # Clone thru proxy from public github (i.e. for plugins, etc.)
+    local repo_relative_path=$1 # e.g. tomsawyer/becky.git maps to https://github.com/tomsawyer/becky.git
+    local targetDir=$2  # Ok to let this default.
+
+    [[ -x $XGIT ]] || errExit "Can't find $XGIT on machine $(hostname)"
+
+    echo "Cloning $repo_relative_path from github.com:"
+    $XGIT -c http.proxy="$github_proxy" -c http.sslverify=false clone "https://github.com/${repo_relative_path}" $targetDir || errExit "Failed cloning $repo_relative_path from github.com"
+}
+
 
